### ISSUE TITLE
doc_fragment location needs to be customizable

### ISSUE THREAD

**Issue by sdodsley** [xlab-steampunk/ansible-doc-extractor#7]
After moving to the use of Collections Ansible will no longer have the doc fragments files in the same old Ansible directory of `ansible/plugins/doc_fragments`
Each collection will have these in their own `doc_fragments` directory, eg `ansible_collections/<namespace>/<collection>/plugins/doc_fragments`.

Need a way to override the directory you are expecting the doc fragments for a collection to exist.

**Comment by tadeboro** [comment]
This already works since we delegate all the real work of assembling the documentation directly to Ansible. If ansible-doc can display your documentation, documentation extractor can render it.

Or do you have an example where things do not work as expected? We are using this piece of code on our collections and we never had a problem with document fragments.

**Comment by sdodsley** [comment]
Yes - this is the error I get, but if I move the doc_fragment in my collection to the old location in core ansible it works. 
`ansible-doc` doesn't work because the module referred to is not in the core upstream modules, only in the collection - unless I'm missing a setting for `ansible-doc`

```
# ansible-doc-extractor ./docs ~/FlashArray-Collection/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pod.py
Rendering /root/FlashArray-Collection/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pod.py
Traceback (most recent call last):
  File "/usr/local/bin/ansible-doc-extractor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ansible_doc_extractor/cli.py", line 127, in main
    render_docs(args.output, args.module, args.template)
  File "/usr/local/lib/python2.7/dist-packages/ansible_doc_extractor/cli.py", line 93, in render_docs
    render_module_docs(output, module, template)
  File "/usr/local/lib/python2.7/dist-packages/ansible_doc_extractor/cli.py", line 60, in render_module_docs
    module, fragment_loader,
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.10.0.dev0-py2.7.egg/ansible/utils/plugin_docs.py", line 128, in get_docstring
    add_fragments(data['doc'], filename, fragment_loader=fragment_loader)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.10.0.dev0-py2.7.egg/ansible/utils/plugin_docs.py", line 116, in add_fragments
    raise AnsibleError('unknown doc_fragment(s) in file {0}: {1}'.format(filename, to_native(', '.join(unknown_fragments))))
ansible.errors.AnsibleError: unknown doc_fragment(s) in file /root/FlashArray-Collection/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pod.py: purestorage.fa
```

**Comment by tadeboro** [comment]
You missed this note in our README file:

> Note
>
> Always extract documentation from the installed collection. The documentation fragment loader fails to combine various parts of the documentation otherwise.

You can "install" your collection in many different ways, but the simplest one is to set the `ANSIBLE_COLLECTIONS_PATHS` variable. If your collection is stored in the `/path/to/some/folder/ansible_collections/your_namespace/your_collection`, then you should run:

    $ export ANSIBLE_COLLECTIONS_PATHS=/path/to/some/folder

This will also fix the ansible-doc.

**Comment by tadeboro** [comment]
@sdodsley Did you manage to get this working or is there anythng else that needs to be done on the extractor's side?

**Comment by tadeboro** [comment]
Closing since there was no response for more than a year.
